include:
  - _base/common-base.yml

services:
  db:
    volumes:
      - ./_data/postgres-db/:/var/lib/postgresql/data
      - ./_data/init-db:/docker-entrypoint-initdb.d

  codelist-repo:
    volumes:
      - ./_data/logs/codelist-repo:/opt/ingrid/ingrid-codelist-repository/logs
      - ./_data/codelist-repository:/opt/ingrid/ingrid-codelist-repository/data

  elastic:
    volumes:
      - ./_data/elasticsearch_data:/usr/share/elasticsearch/data

  ibus:
    volumes:
      - ./_data/logs/ibus:/opt/ingrid/ingrid-ibus/logs
      - ./ibus/conf/activatedIplugs.properties:/opt/ingrid/ingrid-ibus/conf/activatedIplugs.properties

  editor:
    volumes:
      - ./_data/ingrid-editor/upload:/tmp/ingrid/upload-ingrid-editor
      - ./ingrid-editor/codelists:/codelists

  portal:
    volumes:
      - grav:/var/www/portal
      - ./_data/logs/portal:/var/www/portal/logs
      - ./portal/user/:/var/www/portal/user/

  mapclient:
    volumes:
      - ./map/application.override.properties:/usr/local/tomcat/webapps/ingrid-webmap-client/WEB-INF/classes/application.override.properties
      - ./map/WebmapClientData:/opt/ingrid/WebmapClientData

  harvester:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./harvester/config/config.json:/opt/ingrid/harvester/server/config.json
      - ./harvester/config/client_config.json:/opt/ingrid/harvester/server/app/webapp/assets/config.json

  interface-csw:
    volumes:
      - ./_data/logs/interface-csw:/opt/ingrid/ingrid-interface-csw/logs
      - ./_data/interface-csw/instances:/opt/ingrid/ingrid-interface-csw/instances
      - ./interface-csw/conf/config.override.properties:/opt/ingrid/ingrid-interface-csw/conf/config.override.properties
      - ./interface-csw/conf/csw-t.realm.properties:/opt/ingrid/ingrid-interface-csw/conf/csw-t.realm.properties

  interface-search:
    volumes:
      - ./_data/logs/interface-search:/opt/ingrid/ingrid-interface-search/logs
      - ./interface-search/interface-search.properties:/opt/ingrid/ingrid-interface-search/conf/interface-search.properties
      - ./interface-search/descriptor.xml:/opt/ingrid/ingrid-interface-search/conf/descriptor.xml
      - ./interface-search/communication.xml:/opt/ingrid/ingrid-interface-search/conf/communication.xml


volumes:
  grav:
