services:
  #>> remove if you want to use a system-wide sslproxy
  sslproxy:
    # https://github.com/linuxserver/docker-swag
    #image: linuxserver/swag:version-1.15.0
    image: linuxserver/swag:latest
    environment:
      - STAGING=false
      - EMAIL=${SERVER_ADMIN}
      - VALIDATION=http
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=${HOST}
      # - SUBDOMAINS=wildcard
      # - SUBDOMAINS=www,dev,staging,production
    restart: unless-stopped
    volumes:
      - ./_data/sslproxy:/config
      - ./sslproxy/nginx.conf:/config/nginx/site-confs/default.conf
    networks:
      - informationgrid-network
    ports:
      - 443:443
      - 80:80
    #  - 127.0.0.1:443:443
    #  - 127.0.0.1:80:80
    cap_add:
      - NET_ADMIN
  #<<

  postgres-db:
    image: postgres:15.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_DB_ADMIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./_data/postgres-db/:/var/lib/postgresql/data
      - ./_data/init-db:/docker-entrypoint-initdb.d
    networks:
      - informationgrid-network

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
    networks:
      - informationgrid-network

  apache:
    image: httpd:2.4
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - portal
    volumes:
      - ./apache/passwdfile.ingrid:/usr/local/apache2/passwdfile.ingrid
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/vhost.conf:/usr/local/apache2/conf/extra/ingrid.conf
    # comment in if you want to replace the default sslproxy with a system-wide proxy
    #ports:
       #- 127.0.0.1:80:80
    networks:
      - informationgrid-network

  codelist-repo:
    image: docker-registry.wemove.com/ingrid-codelist-repository:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - forceUpdateCodelists=true
      - CREDENTIALS_ADMIN=admin=>${CODELIST_PASSWORD}
    volumes:
      - ./_data/logs/codelist-repo:/opt/ingrid/ingrid-codelist-repository/logs
      - ./_data/codelist-repository:/opt/ingrid/ingrid-codelist-repository/data
      # PATCHES MUST NOT BE MAPPED! NEW PATCHES WON'T BE EXECUTED! Use 'docker cp' if you must.
      #- ./codelist-repository/patches:/opt/ingrid/ingrid-codelist-repository/patches
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - cluster.name=ingrid
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - http.cors.enabled=true
      - "ES_JAVA_OPTS=-Xmx4g -Dlog4j2.formatMsgNoLookups=true"
      - "LOG4J_FORMAT_MSG_NO_LOOKUPS=true"
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      
      # make esdata directory writable to container process
      # to obtain the user 'exec bash' into container
      # the adapt the rights of esdata
      # mkdir -p elastic/_data/esdata
      # chown 1000 elastic/_data/esdata
    volumes:  
      - ./_data/elasticsearch_data:/usr/share/elasticsearch/data
    
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - informationgrid-network

  ibus:
    image: docker-registry.wemove.com/ingrid-ibus:7.5.2
    depends_on:
      - elastic
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - CODELIST_URL=http://codelist-repo:8080
      - CODELIST_USERNAME=admin
      - CODELIST_PASSWORD=${CODELIST_PASSWORD}
      - IBUS_PASSWORD=${ADMIN_GUI_PASSWORD_HASH}
      - JAVA_OPTS=-Xmx384m
      - ELASTIC_HOSTS=elastic:9200
    volumes:
      - ./_data/logs/ibus:/opt/ingrid/ingrid-ibus/logs
      - ./ibus/conf/activatedIplugs.properties:/opt/ingrid/ingrid-ibus/conf/activatedIplugs.properties
      - ./ibus/conf/application-default.properties:/opt/ingrid/ingrid-ibus/conf/application-default.properties
    #ports:
    #  - 127.0.0.1:12300:9900
    command: ["sh", "wait-for-elasticsearch.sh", "elastic:9200", "/bin/sh start.sh start"]
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - informationgrid-network

  ige-ng:
    image: docker-registry.wemove.com/ingrid-ige-ng:7.5.2
   # Workaround build to deploy locally. Not neccessary if using CA's which are already in the JVM Truststore
   #build:
   #  context: ./ige-ng/build
   #  args: 
   #    - IGE_NG_VERSION=7.3.2
   #    - CERT_FILE_NAME_1=fullchain.pem
   #    - CERT_FILE_NAME_2=privkey.pem
    restart: unless-stopped
    depends_on:
      - postgres-db
    user: "1000:1000"
    environment:
      - TZ=Europe/Berlin
      - CONTEXT_PATH=/ige-ng
      - BROKER_URL=wss://${HOST}/ige-ng/ws
      - _JAVA_OPTIONS=-Xmx2g -Dstorage.diskCache.bufferSize=256 -Dspring.profiles.active=elasticsearch,ingrid,ibus,codelist-repo
      #- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8699
      #- KEYCLOAK_CLIENT_ID=ige-ng
      - DATABASE_HOST=postgres-db
      - DATABASE_USERNAME=${POSTGRES_DB_ADMIN}
      - DATABASE_PASSWORD=${POSTGRES_DB_PASSWORD}
      - KEYCLOAK_URL=http://keycloak:8080/keycloak
      - KEYCLOAK_URL_FRONTEND=http://${HOST}/keycloak
      - CODELIST_REPO_URL=http://codelist-repo:8080
      - CODELIST_REPO_USER=admin
      - CODELIST_REPO_PASSWORD=${CODELIST_PASSWORD}
      - APP_HOST_URL=http://${HOST}/ige-ng
      - WAIT_FOR_PARAM=postgres-db:5432
      - MAIL_FROM=
      - KEYCLOAK_BACKEND_USER=ige
      - KEYCLOAK_BACKEND_USER_PASSWORD=admin
      - SHOW_SWAGGER_UI=true
  #  ports:
  #    - "8699:8699"
      #- "8083:80"
    networks:
      - informationgrid-network
    volumes:
      - ./ige-ng/application-ingrid.properties:/app/resources/application-ingrid.properties
      - ./_data/ige-ng/upload:/tmp/ingrid/upload-ige-ng
      - ./ige-ng/codelists:/codelists

  keycloak:
    image: docker-registry.wemove.com/keycloak:26.2.4-1
    restart: unless-stopped
    environment:
      - SIMPLE_SECURITY=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/keycloak
      - KC_HOSTNAME=http://${HOST}/keycloak
     #- KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
        #- KC_HOSTNAME_STRICT_HTTPS=false
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-db
      - KC_DB_USERNAME=${POSTGRES_DB_ADMIN}
      - KC_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - MAIL_SMTP=mailrelay
      - MAIL_FROM=
     #- IGE_CLIENT_ID=ige-ng
     #- IGE_FRONTEND_URL=http://${HOST}/ige-ng
     # - IGE_CLIENT_REDIRECT_URI=
      - IGE_SUPER_USER_LOGIN=ige
      - IGE_SUPER_USER_PASSWORD=admin
      - IGE_SUPER_USER_FIRSTNAME=Super
      - IGE_SUPER_USER_LASTNAME=User
      - IGE_SUPER_USER_EMAIL=
      #- ORGANIZATION="${HOST} Ministerium für Umwelt, Energie und Klimaschutz"
      #- IMPRINT_URL=http://${HOST}/impressum
      #- PRIVACY_NOTE_URL=http://${HOST}/datenschutzbestimmung
      # - ADDITIONAL_REDIRECT_URIS=http://localhost:4300/*

    networks:
      - informationgrid-network


  portal:
    image: docker-registry.wemove.com/ingrid-portal:7.5.2
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Dfile.encoding=UTF8
      - DB_URL_PORTAL=jdbc:postgresql://postgres-db:5432/ingrid_portal
      - DB_URL_MDEK=jdbc:postgresql://postgres-db:5432/mdek
      - DB_DRIVERCLASS=org.postgresql.Driver
      - DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - DB_USER=${POSTGRES_DB_ADMIN}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - QUARTZ_DRIVERCLASS=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      # enable/disable IGE web application in portal container
      - IGE_DISABLED=true
      - PORTAL_SERVER_CONNECTOR_ATTR=proxyPort="443" scheme="https" secure="true"
    volumes:
      - ./_data/logs/ingrid-portal:/opt/ingrid/ingrid-portal/apache-tomcat/logs
      - ./_data/portal/upload:/tmp/ingrid/upload
      - ./_data/portal/WebmapClientData:/opt/ingrid/WebmapClientData
      # add some configurations inside the docker image!? those without database settings!
      - ./portal/test_files:/opt/ingrid/ingrid-portal/apache-tomcat/webapps/ROOT/test_files
      - ./portal/mdek.override.properties:/opt/ingrid/ingrid-portal/apache-tomcat/webapps/ingrid-portal-mdek-application/WEB-INF/classes/mdek.override.properties
      - ./portal/ingrid-portal-apps.override.properties:/opt/ingrid/ingrid-portal/apache-tomcat/webapps/ingrid-portal-apps/WEB-INF/classes/ingrid-portal-apps.override.properties
      - ./portal/application.override.properties:/opt/ingrid/ingrid-portal/apache-tomcat/webapps/ingrid-webmap-client/WEB-INF/classes/application.override.properties
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - informationgrid-network
    command: ["bash", "./wait-for-it.sh", "postgres-db:5432", "-t", "120", "--", "./run.sh"]

  mailrelay:
    image: simenduev/postfix-relay:1.4.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - ACCEPTED_NETWORKS=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - USE_TLS=yes
    logging:
      driver: journald
      options:
        tag: "docker {{.Name}}"
    networks:
      - informationgrid-network

  iplug-sns:
    image: docker-registry.wemove.com/ingrid-iplug-sns:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/sns:/opt/ingrid/ingrid-iplug-sns/logs
      - ./iplug-sns/conf/config.override.properties:/opt/ingrid/ingrid-iplug-sns/conf/config.override.properties
      - ./iplug-sns/conf/spring/external-services.xml:/opt/ingrid/ingrid-iplug-sns/conf/spring/external-services.xml
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

  iplug-opensearch:
    image: docker-registry.wemove.com/ingrid-iplug-opensearch:7.4.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/opensearch:/opt/ingrid/ingrid-iplug-opensearch/logs
      - ./iplug-opensearch/conf/config.override.properties:/opt/ingrid/ingrid-iplug-opensearch/conf/config.override.properties
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

  iplug-se:
    image: docker-registry.wemove.com/ingrid-iplug-se:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - NETWORK_HOST=elastic
    volumes:
      - ./_data/logs/se:/opt/ingrid/ingrid-iplug-se/logs
      - ./_data/iplug-se/database:/opt/ingrid/ingrid-iplug-se/database
      - ./_data/iplug-se/instances:/opt/ingrid/ingrid-iplug-se/instances
      - ./_data/iplug-se/elastic-search-data:/opt/ingrid/ingrid-iplug-se/elastic-search-data
      - ./iplug-se/conf/config.override.properties:/opt/ingrid/ingrid-iplug-se/conf/config.override.properties
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - informationgrid-network

  interface-csw:
    image: docker-registry.wemove.com/ingrid-interface-csw:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/interface-csw:/opt/ingrid/ingrid-interface-csw/logs
      - ./_data/interface-csw/instances:/opt/ingrid/ingrid-interface-csw/instances
      - ./interface-csw/conf/config.override.properties:/opt/ingrid/ingrid-interface-csw/conf/config.override.properties
      - ./interface-csw/conf/csw-t.realm.properties:/opt/ingrid/ingrid-interface-csw/conf/csw-t.realm.properties
    deploy:
      resources:
        limits:
          memory: 384M
    networks:
      - informationgrid-network

  interface-search:
    image: docker-registry.wemove.com/ingrid-interface-search:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/interface-search:/opt/ingrid/ingrid-interface-search/logs
      - ./interface-search/interface-search.properties:/opt/ingrid/ingrid-interface-search/conf/interface-search.properties
      - ./interface-search/descriptor.xml:/opt/ingrid/ingrid-interface-search/conf/descriptor.xml
      - ./interface-search/communication.xml:/opt/ingrid/ingrid-interface-search/conf/communication.xml
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

  iplug-csw:
    image: docker-registry.wemove.com/ingrid-iplug-csw-dsc:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/csw-dsc:/opt/ingrid/ingrid-iplug-csw-dsc/logs
      - ./iplug-csw/conf/config.override.properties:/opt/ingrid/ingrid-iplug-csw-dsc/conf/config.override.properties
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

  iplug-wfs:
    image: docker-registry.wemove.com/ingrid-iplug-wfs-dsc:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/wfs-dsc:/opt/ingrid/ingrid-iplug-wfs-dsc/logs
      - ./iplug-wfs/conf/config.override.properties:/opt/ingrid/ingrid-iplug-wfs-dsc/conf/config.override.properties
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

  iplug-wfs-zdm:
    image: docker-registry.wemove.com/ingrid-iplug-wfs-dsc:7.5.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./_data/logs/wfs-dsc:/opt/ingrid/ingrid-iplug-wfs-dsc/logs
      - ./iplug-wfs-zdm/conf/config.override.properties:/opt/ingrid/ingrid-iplug-wfs-dsc/conf/config.override.properties
      - ./iplug-wfs-zdm/conf/spring/spring.xml:/opt/ingrid/ingrid-iplug-wfs-dsc/webapp/WEB-INF/spring.xml
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - informationgrid-network

networks:
  informationgrid-network:
    driver: "bridge"
